//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.davidhaitch.crdroid;

import android.os.Bundle;
import android.os.Handler;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ListView;
import com.davidhaitch.crdroid.R.layout;

public final class ChatFragment_
    extends ChatFragment
{

    private View contentView_;
    private Handler handler_ = new Handler();

    private void init_(Bundle savedInstanceState) {
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void afterSetContentView_() {
        chatListView = ((ListView) findViewById(com.davidhaitch.crdroid.R.id.chatListView));
        chatMessageBox = ((EditText) findViewById(com.davidhaitch.crdroid.R.id.chatMessageBox));
        sendMessageButton = ((Button) findViewById(com.davidhaitch.crdroid.R.id.sendMessageButton));
        {
            View view = findViewById(com.davidhaitch.crdroid.R.id.sendMessageButton);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ChatFragment_.this.onSendMessageClick();
                    }

                }
                );
            }
        }
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.fragment_chat, container, false);
        }
        return contentView_;
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        afterSetContentView_();
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    public static ChatFragment_.FragmentBuilder_ builder() {
        return new ChatFragment_.FragmentBuilder_();
    }

    @Override
    public void ReframeChatView() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    ChatFragment_.super.ReframeChatView();
                } catch (RuntimeException e) {
                    Log.e("ChatFragment_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void SetUpChatView() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    ChatFragment_.super.SetUpChatView();
                } catch (RuntimeException e) {
                    Log.e("ChatFragment_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public ChatFragment build() {
            ChatFragment_ fragment_ = new ChatFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
