//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.davidhaitch.crdroid;

import android.os.Bundle;
import android.os.Handler;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.TextView;
import com.davidhaitch.crdroid.R.layout;
import com.googlecode.androidannotations.api.BackgroundExecutor;

public final class RadioFragment_
    extends RadioFragment
{

    private View contentView_;
    private Handler handler_ = new Handler();

    private void init_(Bundle savedInstanceState) {
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void afterSetContentView_() {
        artist = ((TextView) findViewById(com.davidhaitch.crdroid.R.id.artist));
        PlayButton = ((Button) findViewById(com.davidhaitch.crdroid.R.id.PlayButton));
        title = ((TextView) findViewById(com.davidhaitch.crdroid.R.id.title));
        ListenersTextView = ((TextView) findViewById(com.davidhaitch.crdroid.R.id.ListenersTextView));
        {
            View view = findViewById(com.davidhaitch.crdroid.R.id.PlayButton);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        RadioFragment_.this.OnClickPlay();
                    }

                }
                );
            }
        }
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.fragment_radio, container, false);
        }
        return contentView_;
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        afterSetContentView_();
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    public static RadioFragment_.FragmentBuilder_ builder() {
        return new RadioFragment_.FragmentBuilder_();
    }

    @Override
    public void SetButtonState() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    RadioFragment_.super.SetButtonState();
                } catch (RuntimeException e) {
                    Log.e("RadioFragment_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void UpdateStats() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    RadioFragment_.super.UpdateStats();
                } catch (RuntimeException e) {
                    Log.e("RadioFragment_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void LoadStatsLoop() {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    RadioFragment_.super.LoadStatsLoop();
                } catch (RuntimeException e) {
                    Log.e("RadioFragment_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void OperateRadio() {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    RadioFragment_.super.OperateRadio();
                } catch (RuntimeException e) {
                    Log.e("RadioFragment_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void LoadStats() {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    RadioFragment_.super.LoadStats();
                } catch (RuntimeException e) {
                    Log.e("RadioFragment_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public RadioFragment build() {
            RadioFragment_ fragment_ = new RadioFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
