//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.davidhaitch.crdroid;

import android.content.Context;
import android.content.Intent;
import android.util.Log;
import com.googlecode.androidannotations.api.BackgroundExecutor;

public final class ScheduleLoaderService_
    extends ScheduleLoaderService
{


    private void init_() {
    }

    @Override
    public void onCreate() {
        init_();
        super.onCreate();
    }

    public static ScheduleLoaderService_.IntentBuilder_ intent(Context context) {
        return new ScheduleLoaderService_.IntentBuilder_(context);
    }

    @Override
    public void LoadRawJson() {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    ScheduleLoaderService_.super.LoadRawJson();
                } catch (RuntimeException e) {
                    Log.e("ScheduleLoaderService_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, ScheduleLoaderService_.class);
        }

        public Intent get() {
            return intent_;
        }

        public ScheduleLoaderService_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startService(intent_);
        }

    }

}
